spring.application.name=flip7

spring.datasource.url=jdbc:postgresql://localhost:5432/flip7
spring.datasource.username=flip7_admin
spring.datasource.password=Testflip7!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate

spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Paris

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# port etc.
server.port=3200